### ISSUE TITLE
Mac+AMD: AMD not detected and Intel uses too high of a work group

### ISSUE THREAD

**Issue by andyoneal** [plaidml/plaidml#17]
iMac 2017 with a Radeon Pro 580 and a Core i5-7600K. Compiled and installed PlaidML from source. Installed via the pip wheel.

Ran plaidml-setup:

> PlaidML Setup (0.0.0.dev0)
> 
> Thanks for using PlaidML!
> 
> Some Notes:
>   * Bugs and other issues: https://github.com/plaidml/plaidml
>   * Questions: https://stackoverflow.com/questions/tagged/plaidml
>   * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
>   * PlaidML is licensed under the GNU AGPLv3
>  
> Default Config Devices:
>    No devices.
> 
> Experimental Config Devices:
>    intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0 : Intel Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
> 
> Using experimental devices can cause poor performance, crashes, and other nastiness.
> Enable experimental device support? (y,n)[n]:y
> 
> PlaidML sends anonymous usage statistics to help guide improvements.
> We'd love your help making it better.
> 
> Enable telemetry reporting? (y,n)[y]:y
> 
> Almost done. Multiplying some matrices...
> Tile code:
>   function (B[X,Z], C[Z,Y]) -> (A) { A[x,y : X,Y] = +(B[x,z] * C[z,y]); }
> ERROR:plaidml:OpenCL: [CL_INVALID_WORK_GROUP_SIZE] : OpenCL Error : clEnqueueNDRangeKernel failed: total work group size (32) is greater than the device can support (1) (cb=12)
> Whew. That worked.
> 
> Save settings to /Users/andy/.plaidml? (y,n)[y]:y
> Success!

Should a gpu be detected at this point? Is there somewhere I can lower total work group size manually?

New to submitting git issues. Sorry if I'm missing anything.

**Comment by andyoneal** [comment]
Output of clinfo, if helpful.

>  Number of platforms                               1
>   Platform Name                                   Apple
>   Platform Vendor                                 Apple
>   Platform Version                                OpenCL 1.2 (Aug 23 2017 16:35:41)
>   Platform Profile                                FULL_PROFILE
>   Platform Extensions                             cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event
> 
>   Platform Name                                   Apple
> Number of devices                                 2
>   Device Name                                     Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
>   Device Vendor                                   Intel
>   Device Vendor ID                                0xffffffff
>   Device Version                                  OpenCL 1.2 
>   Driver Version                                  1.1
>   Device OpenCL C Version                         OpenCL C 1.2 
>   Device Type                                     CPU
>   Device Available                                Yes
>   Device Profile                                  FULL_PROFILE
>   Max compute units                               4
>   Max clock frequency                             3800MHz
>   Device Partition                                (core)
>     Max number of sub-devices                     0
>     Supported partition types                     None
>   Max work item dimensions                        3
>   Max work item sizes                             1024x1x1
>   Max work group size                             1024
>   Compiler Available                              Yes
>   Linker Available                                Yes
>   Preferred work group size multiple              1
>   Preferred / native vector sizes                 
>     char                                                16 / 16      
>     short                                                8 / 8       
>     int                                                  4 / 4       
>     long                                                 2 / 2       
>     half                                                 0 / 0        (n/a)
>     float                                                4 / 4       
>     double                                               2 / 2        (cl_khr_fp64)
>   Half-precision Floating-point support           (n/a)
>   Single-precision Floating-point support         (core)
>     Denormals                                     Yes
>     Infinity and NANs                             Yes
>     Round to nearest                              Yes
>     Round to zero                                 Yes
>     Round to infinity                             Yes
>     IEEE754-2008 fused multiply-add               Yes
>     Support is emulated in software               No
>     Correctly-rounded divide and sqrt operations  Yes
>   Double-precision Floating-point support         (cl_khr_fp64)
>     Denormals                                     Yes
>     Infinity and NANs                             Yes
>     Round to nearest                              Yes
>     Round to zero                                 Yes
>     Round to infinity                             Yes
>     IEEE754-2008 fused multiply-add               Yes
>     Support is emulated in software               No
>     Correctly-rounded divide and sqrt operations  No
>   Address bits                                    64, Little-Endian
>   Global memory size                              8589934592 (8GiB)
>   Error Correction support                        No
>   Max memory allocation                           2147483648 (2GiB)
>   Unified memory for Host and Device              Yes
>   Minimum alignment for any data type             128 bytes
>   Alignment of base address                       1024 bits (128 bytes)
>   Global Memory cache type                        Read/Write
>   Global Memory cache size                        64
>   Global Memory cache line size                   6291456 bytes
>   Image support                                   Yes
>     Max number of samplers per kernel             16
>     Max size for 1D images from buffer            65536 pixels
>     Max 1D or 2D image array size                 2048 images
>     Base address alignment for 2D image buffers   1 bytes
>     Pitch alignment for 2D image buffers          1 bytes
>     Max 2D image size                             8192x8192 pixels
>     Max 3D image size                             2048x2048x2048 pixels
>     Max number of read image args                 128
>     Max number of write image args                8
>   Local memory type                               Global
>   Local memory size                               32768 (32KiB)
>   Max constant buffer size                        65536 (64KiB)
>   Max number of constant args                     8
>   Max size of kernel argument                     4096 (4KiB)
>   Queue properties                                
>     Out-of-order execution                        No
>     Profiling                                     Yes
>   Prefer user sync for interop                    Yes
>   Profiling timer resolution                      1ns
>   Execution capabilities                          
>     Run OpenCL kernels                            Yes
>     Run native kernels                            Yes
>   printf() buffer size                            1048576 (1024KiB)
>   Built-in kernels                                
>   Device Extensions                               cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_APPLE_fp64_basic_ops cl_APPLE_fixed_alpha_channel_orders cl_APPLE_biased_fixed_point_image_formats cl_APPLE_command_queue_priority
> 
>   Device Name                                     AMD Radeon Pro 580 Compute Engine
>   Device Vendor                                   AMD
>   Device Vendor ID                                0x1021c00
>   Device Version                                  OpenCL 1.2 
>   Driver Version                                  1.2 (Aug 24 2017 22:09:54)
>   Device OpenCL C Version                         OpenCL C 1.2 
>   Device Type                                     GPU
>   Device Available                                Yes
>   Device Profile                                  FULL_PROFILE
>   Max compute units                               36
>   Max clock frequency                             1200MHz
>   Device Partition                                (core)
>     Max number of sub-devices                     0
>     Supported partition types                     None
>   Max work item dimensions                        3
>   Max work item sizes                             256x256x256
>   Max work group size                             256
>   Compiler Available                              Yes
>   Linker Available                                Yes
>   Preferred work group size multiple              64
>   Preferred / native vector sizes                 
>     char                                                 4 / 4       
>     short                                                2 / 2       
>     int                                                  1 / 1       
>     long                                                 1 / 1       
>     half                                                 0 / 0        (n/a)
>     float                                                1 / 1       
>     double                                               1 / 1        (cl_khr_fp64)
>   Half-precision Floating-point support           (n/a)
>   Single-precision Floating-point support         (core)
>     Denormals                                     No
>     Infinity and NANs                             Yes
>     Round to nearest                              Yes
>     Round to zero                                 Yes
>     Round to infinity                             Yes
>     IEEE754-2008 fused multiply-add               No
>     Support is emulated in software               No
>     Correctly-rounded divide and sqrt operations  Yes
>   Double-precision Floating-point support         (cl_khr_fp64)
>     Denormals                                     Yes
>     Infinity and NANs                             Yes
>     Round to nearest                              Yes
>     Round to zero                                 Yes
>     Round to infinity                             Yes
>     IEEE754-2008 fused multiply-add               Yes
>     Support is emulated in software               No
>     Correctly-rounded divide and sqrt operations  No
>   Address bits                                    32, Little-Endian
>   Global memory size                              8589934592 (8GiB)
>   Error Correction support                        No
>   Max memory allocation                           2147483648 (2GiB)
>   Unified memory for Host and Device              No
>   Minimum alignment for any data type             128 bytes
>   Alignment of base address                       32768 bits (4096 bytes)
>   Global Memory cache type                        None
>   Image support                                   Yes
>     Max number of samplers per kernel             16
>     Max size for 1D images from buffer            65536 pixels
>     Max 1D or 2D image array size                 2048 images
>     Base address alignment for 2D image buffers   256 bytes
>     Pitch alignment for 2D image buffers          256 bytes
>     Max 2D image size                             16384x16384 pixels
>     Max 3D image size                             2048x2048x2048 pixels
>     Max number of read image args                 128
>     Max number of write image args                8
>   Local memory type                               Local
>   Local memory size                               32768 (32KiB)
>   Max constant buffer size                        65536 (64KiB)
>   Max number of constant args                     8
>   Max size of kernel argument                     1024
>   Queue properties                                
>     Out-of-order execution                        No
>     Profiling                                     Yes
>   Prefer user sync for interop                    Yes
>   Profiling timer resolution                      40ns
>   Execution capabilities                          
>     Run OpenCL kernels                            Yes
>     Run native kernels                            No
>   printf() buffer size                            134217728 (128MiB)
>   Built-in kernels                                
>   Device Extensions                               cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_image2d_from_buffer cl_khr_depth_images cl_APPLE_command_queue_priority cl_APPLE_command_queue_select_compute_units cl_khr_fp64
> 
> NULL platform behavior
>   clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Apple
>   clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [P0]
>   clCreateContext(NULL, ...) [default]            Success [P0]
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
>     Platform Name                                 Apple
>     Device Name                                   AMD Radeon Pro 580 Compute Engine
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
>     Platform Name                                 Apple
>     Device Name                                   Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
>     Platform Name                                 Apple
>     Device Name                                   AMD Radeon Pro 580 Compute Engine
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  <checkNullCtxFromType:2437: create context from type CL_DEVICE_TYPE_CUSTOM : error -30>
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (2)
>     Platform Name                                 Apple
>     Device Name                                   AMD Radeon Pro 580 Compute Engine
>     Device Name                                   Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
> 	NOTE:	your OpenCL library only supports OpenCL 1.0,
> 		but some installed platforms support OpenCL 1.2.
> 		Programs using 1.2 features may crash
> 		or behave unexepectedly

**Comment by choongng** [comment]
Hi Andy, can you run `clinfo` and attach the output?

**Comment by andyoneal** [comment]
beat you by 3 seconds :)

**Comment by earhart** [comment]
FYI, we have a repro; we're working on a fix.

**Comment by jbruestle** [comment]
There appear to be two issues are play here.  The first is a problem with our experimental configurations file.  Specifically: the regex matches for device vendor names in plaidml/experimental.json don't match the value OS X uses.  I tried to update them (I'm having a similar problem on a machine here), but it didn't fix the problem, which indicates that likely we are not reading the vendor name correctly for some reason, which I'm still looking into.

That said, I have a workaround for you:  In plaidml/experimental.json change these lines:
        "sel": {
          "vendor_regex": "Advanced Micro Devices.*"
        },
To:
        "sel": {
          "value": true
        },

This will make plaidml think all of your cards look like experimental AMD style cards.  You can then select your actual AMD device, and everything should work.  

That said, you should know that we are hoping to release an officially supported version of the pips for Mac soon, which will include us testing a number of hardware configurations as well as tuning the various settings, including adding setting for Intel GPU's (which some Macs have).  This can make a huge performance difference (sometimes up to 10X!), so be advised that the quick workaround may not have great perf (although all things being equal, the settings for various AMD cards tend to be similar, so it may be fine).

By the way, thanks for the bug report!  This sort of feedback will really help expand our platform support.  If you would like to be a beta tester for the official Mac release, email info@vertex.ai and we can add you to the list.

**Comment by jbruestle** [comment]
Also, looks like we left -c opt out of the config file (we use a different build process internally).  We're putting in a new commit to fix that, but in the meantime, please add that to your bazel build line.

**Comment by andyoneal** [comment]
I struggled with bazel (due to inexperience, I'm sure) and only got it to build using "bazel build //plaidml:wheel". I imagine this isn't the correct way and I'm not sure where to add -c.

Regardless, editing experimental.json as suggested above seems to work.

> PlaidML Setup (0.0.0.dev0)
> 
> Thanks for using PlaidML!
> 
> Some Notes:
>   * Bugs and other issues: https://github.com/plaidml/plaidml
>   * Questions: https://stackoverflow.com/questions/tagged/plaidml
>   * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
>   * PlaidML is licensed under the GNU AGPLv3
>  
> Default Config Devices:
>    No devices.
> 
> Experimental Config Devices:
>    amd_radeon_pro_580_compute_engine.0 : AMD AMD Radeon Pro 580 Compute Engine
>    intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0 : Intel Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
> 
> Using experimental devices can cause poor performance, crashes, and other nastiness.
> Enable experimental device support? (y,n)[n]:y
> 
> Multiple devices detected (You can override by setting PLAIDML_DEVICE_IDS).
> Please choose a default device:
> 
>    1 : amd_radeon_pro_580_compute_engine.0
>    2 : intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0
> 
> Default device? (1,2)[1]:1
> 
> PlaidML sends anonymous usage statistics to help guide improvements.
> We'd love your help making it better.
> 
> Enable telemetry reporting? (y,n)[y]:y
> 
> Almost done. Multiplying some matrices...
> Tile code:
>   function (B[X,Z], C[Z,Y]) -> (A) { A[x,y : X,Y] = +(B[x,z] * C[z,y]); }
> Whew. That worked.
> 
> Save settings to /Users/andy/.plaidml? (y,n)[y]:y
> Success!


Plaidbench:

> Andys-iMac-2:plaidbench andy$ python plaidbench.py mobilenet
> Using PlaidML backend.
> INFO:plaidml:Initializing device intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0: "Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz", vendor "Intel"
> INFO:plaidml:Initializing device amd_radeon_pro_580_compute_engine.0: "AMD Radeon Pro 580 Compute Engine", vendor "AMD"
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0": "AMD AMD Radeon Pro 580 Compute Engine"
> 
> Model loaded.
> Compiling and running initial batch, batch_size=1
> INFO:plaidml:Analyzing Ops: 192 of 374 operations complete
> Warmup
> Doing the main timing
> Example finished, elapsed: 5.92681694031 (compile), 12.0857377052 (execution)

**Comment by andyoneal** [comment]
using 7e0070c, plaidbench improved on compile time:

> Using PlaidML backend.
> INFO:plaidml:Initializing device intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0: "Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz", vendor "Intel"
> INFO:plaidml:Initializing device amd_radeon_pro_580_compute_engine.0: "AMD Radeon Pro 580 Compute Engine", vendor "AMD"
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0": "AMD AMD Radeon Pro 580 Compute Engine"
> 
> Model loaded.
> Compiling and running initial batch, batch_size=1
> INFO:plaidml:Analyzing Ops: 153 of 374 operations complete
> Warmup
> Doing the main timing
> Example finished, elapsed: 2.88862299919 (compile), 11.8895916939 (execution)
> Andys-iMac-2:plaidbench andy$ python plaidbench.py mobilenet
> Using PlaidML backend.
> INFO:plaidml:Initializing device intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0: "Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz", vendor "Intel"
> INFO:plaidml:Initializing device amd_radeon_pro_580_compute_engine.0: "AMD Radeon Pro 580 Compute Engine", vendor "AMD"
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0": "AMD AMD Radeon Pro 580 Compute Engine"
> 
> Model loaded.
> Compiling and running initial batch, batch_size=1
> INFO:plaidml:Analyzing Ops: 231 of 374 operations complete
> Warmup
> Doing the main timing
> Example finished, elapsed: 2.91934394836 (compile), 11.6020669937 (execution)

**Comment by brianretford** [comment]
Compile time usually drops on the second run as most cards include a cache for compiled kernels. If you set a different batch-size, I would expect the compile time to go up for the first run, and then down

**Comment by andyoneal** [comment]
Got it. Switching to a new benchmark then.

> Andys-iMac-2:plaidbench andy$ python plaidbench.py inception_v3
> Using PlaidML backend.
> INFO:plaidml:Initializing device intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0: "Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz", vendor "Intel"
> INFO:plaidml:Initializing device amd_radeon_pro_580_compute_engine.0: "AMD Radeon Pro 580 Compute Engine", vendor "AMD"
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0": "AMD AMD Radeon Pro 580 Compute Engine"
> Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.5/inception_v3_weights_tf_dim_ordering_tf_kernels.h5
> 96051200/96112376 [============================>.] - ETA: 0s  
> Model loaded.
> Compiling and running initial batch, batch_size=1
> INFO:plaidml:Analyzing Ops: 30 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 84 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 117 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 133 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 210 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 226 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 303 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 319 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 374 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 527 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 736 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 947 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 973 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 1084 of 1150 operations complete
> Warmup
> Doing the main timing
> Example finished, elapsed: 67.8232870102 (compile), 85.6556134224 (execution)

**Comment by brianretford** [comment]
Yeah as I noted above AMD does not actually seem to cache opencl compilations, so the speedup was all -c opt. One thing we've noticed on AMD cards is that, at least on linux, it speeds things up a lot if you peg the card to a higher clock speed, which we do with something like:
```
#!/bin/sh
echo set > /sys/class/drm/${1}/device/pp_compute_power_profile
echo profile_peak >  /sys/class/drm/${1}/device/power_dpm_force_performance_level
echo 5 > /sys/class/drm/${1}/device/pp_dpm_sclk
```
Not sure what the equivalent procedure is in os-x. Your results are pretty similar to what we get out of an R9 Nano:

r9nano | mobilenet_infer | 1 | 10.038

**Comment by brianretford** [comment]
Another thing to note is that AMD is much, much faster with a reasonable batch size. We'll figure out why batch size 1 isn't as efficient as it should be eventually. You can try `--batch-size 16` and `--batch_size 32`

**Comment by andyoneal** [comment]
just to finish the benchmarks out. hopefully helpful.

resnet50. gpu at ~50%

> Andys-iMac-2:plaidbench andy$ python plaidbench.py resnet50
> Using PlaidML backend.
> INFO:plaidml:Initializing device intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0: "Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz", vendor "Intel"
> INFO:plaidml:Initializing device amd_radeon_pro_580_compute_engine.0: "AMD Radeon Pro 580 Compute Engine", vendor "AMD"
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0": "AMD AMD Radeon Pro 580 Compute Engine"
> Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels.h5
> 102711296/102853048 [============================>.] - ETA: 0s  
> Model loaded.
> Compiling and running initial batch, batch_size=1
> INFO:plaidml:Analyzing Ops: 31 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 88 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 134 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 180 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 237 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 283 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 329 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 375 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 432 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 478 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 524 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 570 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 616 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 662 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 719 of 809 operations complete
> INFO:plaidml:Analyzing Ops: 765 of 809 operations complete
> Warmup
> Doing the main timing
> Example finished, elapsed: 54.8780171871 (compile), 32.2979290485 (execution)

vgg16. gpu at ~60%

> Andys-iMac-2:plaidbench andy$ python plaidbench.py vgg16
> Using PlaidML backend.
> INFO:plaidml:Initializing device intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0: "Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz", vendor "Intel"
> INFO:plaidml:Initializing device amd_radeon_pro_580_compute_engine.0: "AMD Radeon Pro 580 Compute Engine", vendor "AMD"
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0": "AMD AMD Radeon Pro 580 Compute Engine"
> Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels.h5
> 552665088/553467096 [============================>.] - ETA: 0s   
> Model loaded.
> Compiling and running initial batch, batch_size=1
> INFO:plaidml:Analyzing Ops: 8 of 161 operations complete
> INFO:plaidml:Analyzing Ops: 20 of 161 operations complete
> INFO:plaidml:Analyzing Ops: 31 of 161 operations complete
> INFO:plaidml:Analyzing Ops: 43 of 161 operations complete
> INFO:plaidml:Analyzing Ops: 54 of 161 operations complete
> INFO:plaidml:Analyzing Ops: 65 of 161 operations complete
> INFO:plaidml:Analyzing Ops: 77 of 161 operations complete
> INFO:plaidml:Analyzing Ops: 88 of 161 operations complete
> INFO:plaidml:Analyzing Ops: 99 of 161 operations complete
> INFO:plaidml:Analyzing Ops: 115 of 161 operations complete
> INFO:plaidml:Analyzing Ops: 133 of 161 operations complete
> Warmup
> Doing the main timing
> Example finished, elapsed: 36.0670490265 (compile), 32.9906122684 (execution)

vgg19. gpu at ~64% 

> Andys-iMac-2:plaidbench andy$ python plaidbench.py vgg19
> Using PlaidML backend.
> INFO:plaidml:Initializing device intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0: "Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz", vendor "Intel"
> INFO:plaidml:Initializing device amd_radeon_pro_580_compute_engine.0: "AMD Radeon Pro 580 Compute Engine", vendor "AMD"
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0": "AMD AMD Radeon Pro 580 Compute Engine"
> Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg19_weights_tf_dim_ordering_tf_kernels.h5
> 573808640/574710816 [============================>.] - ETA: 0s   
> Model loaded.
> Compiling and running initial batch, batch_size=1
> INFO:plaidml:Analyzing Ops: 8 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 20 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 31 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 43 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 54 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 65 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 76 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 88 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 99 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 110 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 121 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 133 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 144 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 155 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 166 of 194 operations complete
> Warmup
> Doing the main timing
> Example finished, elapsed: 48.568748951 (compile), 40.7741346359 (execution)

xception. gpu at ~54%.

> Andys-iMac-2:plaidbench andy$ python plaidbench.py vgg19
> Using PlaidML backend.
> INFO:plaidml:Initializing device intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0: "Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz", vendor "Intel"
> INFO:plaidml:Initializing device amd_radeon_pro_580_compute_engine.0: "AMD Radeon Pro 580 Compute Engine", vendor "AMD"
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0": "AMD AMD Radeon Pro 580 Compute Engine"
> Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg19_weights_tf_dim_ordering_tf_kernels.h5
> 573808640/574710816 [============================>.] - ETA: 0s   
> Model loaded.
> Compiling and running initial batch, batch_size=1
> INFO:plaidml:Analyzing Ops: 8 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 20 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 31 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 43 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 54 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 65 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 76 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 88 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 99 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 110 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 121 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 133 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 144 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 155 of 194 operations complete
> INFO:plaidml:Analyzing Ops: 166 of 194 operations complete
> Warmup
> Doing the main timing
> Example finished, elapsed: 48.568748951 (compile), 40.7741346359 (execution)
> Andys-iMac-2:plaidbench andy$ python plaidbench.py xception
> Using PlaidML backend.
> INFO:plaidml:Initializing device intel(r)_core(tm)_i5-7600k_cpu_@_3.80ghz.0: "Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz", vendor "Intel"
> INFO:plaidml:Initializing device amd_radeon_pro_580_compute_engine.0: "AMD Radeon Pro 580 Compute Engine", vendor "AMD"
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0": "AMD AMD Radeon Pro 580 Compute Engine"
> Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.4/xception_weights_tf_dim_ordering_tf_kernels.h5
> 91062272/91884032 [============================>.] - ETA: 0s  
> Model loaded.
> Compiling and running initial batch, batch_size=1
> INFO:plaidml:Analyzing Ops: 68 of 499 operations complete
> INFO:plaidml:Analyzing Ops: 198 of 499 operations complete
> INFO:plaidml:Analyzing Ops: 334 of 499 operations complete
> INFO:plaidml:Analyzing Ops: 455 of 499 operations complete
> Warmup
> Doing the main timing
> Example finished, elapsed: 15.4152550697 (compile), 34.8657810688 (execution)


Don't want to spam this ticket. If re-running with --batch-size 32 is useful, please let me know.

**Comment by brianretford** [comment]
No worries about spamming the issue. Re-running at 32 would be interesting. You should see higher utilization -- batch size 1 is frequently memory constrained

**Comment by andyoneal** [comment]
plaidbench mobilenet. 2nd run for each.

batch_size=1. gpu at ~25%.

> Example finished, elapsed: 0.433942079544 (compile), 9.98788547516 (execution)

batch_size=16. couldn't catch gpu. too fast. highest sample was 16%.

> Example finished, elapsed: 0.541084051132 (compile), 2.35083913803 (execution)

batch_size=32. too fast again to get a good read on gpu. highest sample was 47%.

> Example finished, elapsed: 0.646697044373 (compile), 2.39330601692 (execution)

**Comment by jbruestle** [comment]
Excellent!  Since we do 1024 inferences on each run of plaidbench, that's over 400 frames per second of mobilenet image classifications.

**Comment by jbruestle** [comment]
As of https://github.com/plaidml/plaidml/pull/22, the config issue on Mac should be fixed.  Could you pull, rebuild, reinstall, and give it a go?  Make sure to add -I when doing the reinstall, since the version number will be the same and pip won't update by default.  Also, if your having trouble measuring perf because things are too fast, you can always increase the number of images plaidbench uses.

**Comment by andyoneal** [comment]
Now detects and uses the AMD gpu without edits to experimental.json. Obviously this is the device I would rather use with this machine, but I should add that plaidml-setup still shows the "ERROR:plaidml:OpenCL: [CL_INVALID_WORK_GROUP_SIZE] : OpenCL Error : clEnqueueNDRangeKernel failed: total work group size (32) is greater than the device can support (1) (cb=12)" error if I choose the intel option.

**Comment by andyoneal** [comment]
Just some other benchmarks.

python plaidbench.py --batch-size 16 inception_v3

> Example finished, elapsed: 30.690279007 (compile), 30.4678688049 (execution)

python plaidbench.py --batch-size 32 inception_v3

> Example finished, elapsed: 28.5554969311 (compile), 18.4099912643 (execution)

python plaidbench.py --batch-size 48 inception_v3 

> Example finished, elapsed: 29.608328104 (compile), 22.9525249004 (execution)

python plaidbench.py --batch-size 64 inception_v3 

> Using PlaidML backend.
> INFO:plaidml:Opening device "amd_radeon_pro_580_compute_engine.0
> 
> Model loaded.
> Compiling and running initial batch, batch_size=64
> INFO:plaidml:Analyzing Ops: 210 of 1150 operations complete
> INFO:plaidml:Analyzing Ops: 374 of 1150 operations complete
> Abort trap: 6
