### ISSUE TITLE
Cannot calculate gradient in Keras with PlaidML

### ISSUE THREAD

**Issue by daniloefl** [plaidml/plaidml#223]
Dear authors,

thank you very much for the excellent work done in PlaidML.
Unfortunately, I am trying to use the PlaidML backend in Keras to calculate gradients, but I get the error below.

The objective is to implement the WGAN-GP (Wasserstein GAN with Gradient Penalty term), on which part of the loss function includes a function of the gradient of the WGAN's critic. The error below happens when performing the gradient calculation.

The code works perfectly well if using Tensorflow (but I don't have an Nvidia card and therefore am trying to switch to PlaidML to speed up the training, so that I can use my Intel HD 520 GPU -- not sure if this is related).

The snippet of code used is the following. I have tried several variations, but nothing works. I did manage to calculate the gradient if I substitute `critic(interp_input)` with some dummy code like `K.backend.square(interp_input)`. But this is really not what I want.

The error seems to be related with the derivative of a `simple_reduce` function. The `critic` is a `Model` defined as below (feed-forward network with `LeakyReLU`). I don't see where `simple_reduce` is necessary (or used), given that I want to take the gradient w.r.t. the input and I never attempt to average or sum along the batch axis in the critic. Any help would be appreciated.

Best regards,
Danilo

The problematic piece (alculation of the gradient penalty term):
```
def gradient_penalty_loss(y_true, y_pred, critic, interp_input, Nbatch):
  gradients = K.backend.gradients(critic(interp_input), [interp_input])[0]
  slopes = K.backend.sqrt(1e-8 + K.backend.sum(K.backend.square(gradients), axis = [1]))
  gp = K.backend.mean(K.backend.square(1 - slopes))
  return gp

(...)

   self.interp_input = Input(shape = (1,), name = 'interp_input')

    from functools import partial
    partial_gp_loss = partial(gradient_penalty_loss, interp_input = self.interp_input, critic = self.critic, Nbatch = self.n_batch)

    self.disc_fixed_critic = Model([self.nominal_input, self.syst_input, self.interp_input],
                                   [self.critic(self.discriminator(self.nominal_input)), self.critic(self.discriminator(self.syst_input)), self.critic(self.interp_input)],
                                   name = "disc_fixed_critic")
    self.disc_fixed_critic.compile(loss = [wasserstein_loss, wasserstein_loss, partial_gp_loss],
                                   loss_weights = [1.0, 1.0, self.lambda_gp],
                                   optimizer = Adam(lr = 1e-4, beta_1 = 0, beta_2 = 0.9), metrics = [])

```

The error:
```
Traceback (most recent call last):
  File "./keras_wgangp.py", line 1162, in <module>
    main()
  File "./keras_wgangp.py", line 1125, in main
    network.train()
  File "./keras_wgangp.py", line 690, in train
    sample_weight = [x_batch_nom_w, x_batch_syst_w, positive_y])
  File "/home/daniloefl/workspace/plaidml-py3/lib/python3.6/site-packages/keras/engine/training.py", line 1214, in train_on_batch
    self._make_train_function()
  File "/home/daniloefl/workspace/plaidml-py3/lib/python3.6/site-packages/keras/engine/training.py", line 508, in _make_train_function
    **self._function_kwargs)
  File "/home/daniloefl/workspace/plaidml-py3/lib/python3.6/site-packages/plaidml/keras/backend.py", line 661, in function
    return _Function(inputs, outputs, updates, name)
  File "/home/daniloefl/workspace/plaidml-py3/lib/python3.6/site-packages/plaidml/keras/backend.py", line 137, in __init__
    name=name)
  File "/home/daniloefl/workspace/plaidml-py3/lib/python3.6/site-packages/plaidml/tile.py", line 1052, in compose
    bindings.insert(op, op.bind(bindings))
  File "/home/daniloefl/workspace/plaidml-py3/lib/python3.6/site-packages/plaidml/op.py", line 1724, in bind
    output_vars = plaidml.gradients(loss_var, input_vars)
  File "/home/daniloefl/workspace/plaidml-py3/lib/python3.6/site-packages/plaidml/__init__.py", line 1449, in gradients
    return [Var(_lib().plaidml_compute_grad_wrt(g, var)) for var in variables]
  File "/home/daniloefl/workspace/plaidml-py3/lib/python3.6/site-packages/plaidml/__init__.py", line 1449, in <listcomp>
    return [Var(_lib().plaidml_compute_grad_wrt(g, var)) for var in variables]
  File "/home/daniloefl/workspace/plaidml-py3/lib/python3.6/site-packages/plaidml/__init__.py", line 716, in _check_err
    self.raise_last_status()
  File "/home/daniloefl/workspace/plaidml-py3/lib/python3.6/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Invalid derivative: unknown function simple_reduce
```

The `critic` Model definition:
```
    self.critic_input = Input(shape = (1,), name = 'critic_input')
    xc = self.critic_input
    xc = Dense(100, activation = None, name = "adv_1")(xc)
    xc = K.layers.LeakyReLU(0.2)(xc)
    xc = Dense(50, activation = None, name = "adv_2")(xc)
    xc = K.layers.LeakyReLU(0.2)(xc)
    xc = Dense(20, activation = None, name = "adv_4")(xc)
    xc = K.layers.LeakyReLU(0.2)(xc)
    xc = Dense(1, activation = None, name = "adv_5")(xc)
    self.critic = Model(self.critic_input, xc, name = "critic")
    self.critic.trainable = True
    self.critic.compile(loss = wasserstein_loss,
                        optimizer = Adam(lr = 1e-3), metrics = [])

```

**Comment by daniloefl** [comment]
Dear @wilderrodrigues ,

I saw your bug, but if you look at the code below:
https://github.com/plaidml/plaidml/blob/master/tile/lang/symbolic.cc#L70

You can see that somehow the "simple_reduce" function has some special status and it is explicitly mentioned in the C++ code. Because I don't see how this function is mentioned in the Keras Model, I suspect that it is actually added in the graph by PlaidML itself (perhaps in the code above). This is why I made a separate ticket for it, in case this is caused by the code above.

It could well be that this is a duplicate from your bug, but I am not sure.

Best regards,
Danilo

**Comment by dgkutnic** [comment]
The gradient issue has been addressed in #296 - a fix is pending verification.

**Comment by daniloefl** [comment]
Dear @dgkutnic,

thank you for following up on this. I am now away and will try out the solution as soon as I am back, so it may take a few days, but I will follow up on it.

Best regards,
Danilo

**Comment by daniloefl** [comment]
Dear @dgkutnic,

thank you for the information. Unfortunately, this does not seem to solve the issue using the master of the today's code ( f3991105ad895add5af750b9c318a74d0a9acd14 ), recompiled from scratch to make the PlaidML and PlaidML-Keras wheels. Is this the correct version to use in this test?

The code for the culprit loss function follows in [1] and I can add that replacing it with the commented out first line in the function works without a problem (although it is of course complete nonsense), indicating that, as expected, the issue is with the gradient calculation (which works out of the box with Keras+Tensorflow).

With that first line commented out, as shown in [1], I get as a result the error in [2], which is the same as the reported originally.

If one is interested in further examining the code, the full code in a test tag version can be seen here:
https://github.com/daniloefl/gantest/blob/plaidml-grad-test/keras_wgangp.py

Best regards,
Danilo

[1]
```
def gradient_penalty_loss(y_true, y_pred, critic, interp_input):
  #gradients = interp_input # TEST! Use this to avoid the following code and check if the gradient is the culprit in PlaidML
  gradients = K.backend.gradients(critic(interp_input), [interp_input])[0] # shape = (None, 28, 28, 1)
  ## not needed as there is a single element in interp_input here (the discriminator output)
  ## the only dimension left is the batch, which we just average over in the last step
  slopes = K.backend.sqrt(1e-7 + K.backend.sum(K.backend.square(gradients), axis = [1, 2, 3]))
  gp = K.backend.mean(K.backend.square(1 - slopes))
  return gp
`` 

[2]
```
Traceback (most recent call last):
  File "./keras_wgangp.py", line 579, in <module>
    main()
  File "./keras_wgangp.py", line 555, in main
    network.train(prefix, args.result_dir, args.network_dir)
  File "./keras_wgangp.py", line 350, in train
    sample_weight = [positive_y, positive_y])
  File "/home/daniloefl/anaconda3/envs/plaidml/lib/python3.7/site-packages/keras/engine/training.py", line 1216, in train_on_batch
    self._make_train_function()
  File "/home/daniloefl/anaconda3/envs/plaidml/lib/python3.7/site-packages/keras/engine/training.py", line 519, in _make_train_function
    **self._function_kwargs)
  File "/home/daniloefl/anaconda3/envs/plaidml/lib/python3.7/site-packages/plaidml/keras/backend.py", line 691, in function
    return _Function(inputs, outputs, updates, name)
  File "/home/daniloefl/anaconda3/envs/plaidml/lib/python3.7/site-packages/plaidml/keras/backend.py", line 148, in __init__
    name=name)
  File "/home/daniloefl/anaconda3/envs/plaidml/lib/python3.7/site-packages/plaidml/tile.py", line 1053, in compose
    bindings.insert(op, op.bind(bindings))
  File "/home/daniloefl/anaconda3/envs/plaidml/lib/python3.7/site-packages/plaidml/op.py", line 1705, in bind
    output_vars = plaidml.gradients(loss_var, input_vars)
  File "/home/daniloefl/anaconda3/envs/plaidml/lib/python3.7/site-packages/plaidml/__init__.py", line 1460, in gradients
    return [Var(_lib().plaidml_compute_grad_wrt(g, var)) for var in variables]
  File "/home/daniloefl/anaconda3/envs/plaidml/lib/python3.7/site-packages/plaidml/__init__.py", line 1460, in <listcomp>
    return [Var(_lib().plaidml_compute_grad_wrt(g, var)) for var in variables]
  File "/home/daniloefl/anaconda3/envs/plaidml/lib/python3.7/site-packages/plaidml/__init__.py", line 764, in _check_err
    self.raise_last_status()
  File "/home/daniloefl/anaconda3/envs/plaidml/lib/python3.7/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Invalid derivative: unknown function simple_reduce
(plaidml) daniloefl@daniloefl-laptop:~/workspace/gantest$ 
```

**Comment by dgkutnic** [comment]
Hi @daniloefl,

Sorry for the confusion here. The gradient calculation fix is still pending release to the public repo; however, we do believe that it is caused by the same bug as the other gradient issue. 

I will verify this on our pre-release repo (currently private). Thank you for providing a code sample - it is much appreciated.

Hope this helps. Let me know if you have any questions.

Denise

**Comment by daniloefl** [comment]
Hi @dgkutnic ,

sorry for the misunderstanding. I will then wait the public release of the fix. Let me know if you need me to do further tests.

Best regards,
Danilo

**Comment by xavierign** [comment]
Any update on this? thanks!

**Comment by lucascamel** [comment]
Hi @WenChuanLee,

any update for the fix of "Invalid derivative: unknown function simple_reduce"?

Thanks.

**Comment by FuhrerStein** [comment]
Any chance this bug to be solved?

**Comment by daniloefl** [comment]
I just tried once more with plaidml (& plaidml-keras) 0.7.0 (default version when doing pip install) and the issue persists.

**Comment by FuhrerStein** [comment]
@daniloefl , did you find any workaround for this instance? I ended up using just simple `mse` (mean square error) instead of `gradient_penalty_loss` altogether. It seems to work somehow, but I doubt it's anywhere near optimum. 
Btw, I use plaidML on AMD gpu. That seems to be the only viable option for AMD in Windows for now.

**Comment by daniloefl** [comment]
Hi @FuhrerStein ,

as my goal was to implement a WGAN-GP, this cannot be done without a gradient penalty. An MSE loss should not work (you can try, but it would not be a WGAN-GP). Either way, it has been far too long, and I have moved on: just testing it now, since it would be good to know if PlaidML works.

I have just recompiled plaidml 0.7.0 from the source (but I had to do some corrections in the "tbb" dependency, because its URL has moved: diff to tag 0.7.0 in [*]). With 0.7.0 the problem is still there.

Best regards,
Danilo



[*]
```
daniloefl@daniloefl-laptop:~/Computer/plaidml$ git diff
diff --git a/bzl/workspace.bzl b/bzl/workspace.bzl
index 1f6d51d8..171a7875 100644
--- a/bzl/workspace.bzl
+++ b/bzl/workspace.bzl
@@ -174,9 +174,9 @@ def plaidml_workspace():
 
     http_archive(
         name = "tbb",
-        url = "https://github.com/intel/tbb/archive/tbb_2019.zip",
-        sha256 = "078c969b1bbd6b2afb01f65cf9d513bb80636363b206f1e2ae221b614d7ae197",
-        strip_prefix = "tbb-tbb_2019",
+        url = "https://github.com/oneapi-src/oneTBB/archive/tbb_2019.zip",
+        sha256 = "3bb395989ce4701fc5d486ab8db3d639e9f86111a761de358d8e02bb6ed1e076",
+        strip_prefix = "oneTBB-tbb_2019",
         build_file = clean_dep("//vendor/tbb:tbb.BUILD"),
     )
 

```
