### ISSUE TITLE
Feature Request: Disk cache to increase startup speed

### ISSUE THREAD

**Issue by SleepProgger** [plaidml/plaidml#351]
For big/complex models the "Analyzing ops" phase up to multiple minutes on my system.

And since this phase runs as soon as new tile kernel are required this can even occur multiple times during one run (changed batch size -> new kernel).

Is there a way to cache this so that it survives between runs ?
Optional by setting an environment variable would be fine for me as this only really make sense for big models.

**Comment by brianretford** [comment]
This is not a hard feature to add actually, and it's kind of embarrassing that we haven't added it yet. program_cache.h/.cc do the caching intra-execution it should be easy to add. Denise – maybe Mike can implement this?

**Comment by dgkutnic** [comment]
Sounds like a great plan. I'll sync up with him today about this

**Comment by SleepProgger** [comment]
Is there any news regarding this ?
Otherwise i could spend a weekend on trying to get this running for a PR.

IMO its a much needed feature with plaidmls structure.

**Comment by dgkutnic** [comment]
@SleepProgger IIRC Mike had thought this was already fixed, but if it's not, feel free to go for it.

**Comment by SleepProgger** [comment]
At least with 0.6.4 i still see the `Analyzing Ops messages each time i run a model (even ones i already ran before).
It might be added already in the current master tho ?

**Comment by dgkutnic** [comment]
No, if it's not working on 0.6.4, I'm not very confident that we have worked on anything related to it since then.

**Comment by nfogh** [comment]
Hi.

I was wondering if there has been any progress on this enhancement.

I am trying to figure out how to do it myself. As I can see it, one needs to change the LruCache to be file-backed. So we need to be able to serialize all of the contained items (class Entry). Is this the right way to go about it?
