### ISSUE TITLE
Wrong output dimension with `Dot` layers in plaid ML

### ISSUE THREAD

**Issue by zachmayer** [plaidml/plaidml#358]
Here is a simple keras neural network using a `Dot` layer:
```python
from keras.layers import Input, Dense, Dot
from keras.models import Model

model_in = Input((10,), name='input')
model_out = model_in
model_out = Reshape((-1, 1), name='reshape')(model_out)
model_out = Dot(axes=2, name='dot')([model_out, model_out])
model_out = Flatten(name='flatten')(model_out)
model = Model(model_in, model_out)
model.summary()
```

if I compile this network with tensorflow 1.14.0, the output shape is 100 (which is what I expect, as 10*10 = 100):

```python
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input (InputLayer)              (None, 10)           0                                            
__________________________________________________________________________________________________
reshape (Reshape)               (None, 10, 1)        0           input[0][0]                      
__________________________________________________________________________________________________
dot (Dot)                       (None, 10, 10)       0           reshape[0][0]                    
                                                                 reshape[0][0]                    
__________________________________________________________________________________________________
flatten (Flatten)               (None, 100)          0           dot[0][0]                        
==================================================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
```

However, when I switch my keras backend to `plaidml.keras.backend`, I get an output dimension of 100, which is clearly incorrect:

```python
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input (InputLayer)              (None, 10)           0                                            
__________________________________________________________________________________________________
reshape (Reshape)               (None, 10, 1)        0           input[0][0]                      
__________________________________________________________________________________________________
dot (Dot)                       (None, 10, 10)       0           reshape[0][0]                    
                                                                 reshape[0][0]                    
__________________________________________________________________________________________________
flatten (Flatten)               (None, 10)           0           dot[0][0]                        
==================================================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
```

I'm using plaidml `0.6.1`.  Note that the stated output dimension of the `Dot` layer is correct (10*10), but the output dimension of the `Flatten` layer is incorrect

**Comment by dgkutnic** [comment]
We've found some issues with the way plaidml is handling `reshape`. I'll replicate this model on my end and see whether I can trace this back to the same issue, or whether this is a new issue entirely.

**Comment by zachmayer** [comment]
Gotcha.  I think the error is with the dot layer.  Here's an example, where the output should be `(1,2,2)` but instead is `(1, 2)`:
```python
from keras.layers import Input, Dot
from keras.models import Model
import numpy as np

model_in = Input((2,1), name='input')
model_out = Dot(axes=2, name='dot')([model_in, model_in])
model = Model(model_in, model_out)
x = np.zeros((1,2,1))
model.predict(x)
```
Which yields `array([[0., 0.]], dtype=float32)`

What's interesting is the keras model summary gives the correct output shape for `Dot`: `dot (Dot)                       (None, 2, 2) ` but the prediction shape is `(None, 2)` instead.

If I change the backend to tensorflow, I get the correct shape from the prediction for the same network:
```python
array([[[0., 0.],
        [0., 0.]]], dtype=float32)
```

**Comment by dgkutnic** [comment]
Thanks so much for this test case! This really helps with my debug process.

You are correct in that there is an issue with the `Dot` layer. In the backend, it is calling `BatchDot`, where we had recently modified the broadcast/concatenation structure to add 2D tensor support for a separate function (`K.gradients`, see #296 if interested). When we were making that change, we were not entirely certain that our implementation was returning the correct shape in all test cases, and this confirms that we are still missing some cases.

I'm continuing to look into this and I'll let you know as soon as I know exactly what we were doing wrong here. For now, I'm targeting this into our next release (0.6.2, est. 7/12)

**Comment by zachmayer** [comment]
Thanks!

**Comment by dgkutnic** [comment]
Hey @zachmayer - thank you for your patience on this. 

We've re-looked at the [documentation for `BatchDot`](https://www.tensorflow.org/api_docs/python/tf/keras/backend/batch_dot) as well as the [tensorflow implementation of `BatchDot`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py) and have determined that there's a mismatch in the description of `BatchDot` and TensorFlow's implementation. With that info, we've re-implemented `BatchDot` in a way that makes the most sense to us based on the documentation. It fixes the output shapes in both of your test cases, but the actual values within the tensor may be different than what you see in TensorFlow. Our new implementation will make it into the next release.

If you find that you're having correctness issues with the new implementation of `BatchDot`, or simply would like to have it implemented the same way that TensorFlow does, we'd love for you to write your own implementation of `BatchDot`. Our implementation is in `plaidml/keras/backend.py` if that helps you to get started.

**Comment by zachmayer** [comment]
Would it be worth opening an issue on tensorflow's github about the mismatch?

When you say "the actual values in the tensor may differ" what do you mean?

I'll try out my test case again and see if the results make sense.  I'm not sure I'm up for writing my own implementation of `BatchDot`, but if I'm feeling ambitious, I'll make a PR!

**Comment by dgkutnic** [comment]
It might be worthwhile to open an issue on TensorFlow's github repo. You'd probably want to have a minimal reproduction (i.e. a BatchDot with `x.shape=(1,2,6,2)` and `y.shape=(1,2,2,3)` and `axes = (3, 1)`has an output shape of `(1,2,6,3)`) whereas by the TF definition for output shape "`A tensor with shape equal to the concatenation of x's shape (less the dimension that was summed over) and y's shape (less the batch dimension and the dimension that was summed over). If the final rank is 1, we reshape it to (batch_size, 1).`" sounds like it should have an output shape of (1,2,6,2,3).

We have a testing system that compares value tolerances/shape differences between our implementations and TF's implementations, and when I tested my code against that system, I was seeing some differences in values within the tensors but the same shapes.

I haven't released the code changes yet -- I'll let you know when that happens but for now, it might make sense to file the issue against tensorflow and link us back to that so that we can see whether they are going to change their implementation and/or documentation of `BatchDot`.

**Comment by zachmayer** [comment]
I opened a documentation issue on tensorflow: https://github.com/tensorflow/tensorflow/issues/30846

If the TF devs have questions, will you help answer them?

**Comment by dgkutnic** [comment]
I'd certainly be willing to jump in as needed.
Please note that I'm traveling through 7/23 and responses may be slow during this period of time.

**Comment by dgkutnic** [comment]
Hey @zachmayer - one of my colleagues suggested that I compare `BatchDot` results between TensorFlow and other Keras backends (namely Theano and CNTK). What I'm seeing is that the TensorFlow implementation of `BatchDot` not only mismatches the Keras documentation, but also Theano's implementation (which matches the Keras documentation).

With that being said, I'm going to hold off on any changes that are trying to replicate TensorFlow's behavior when running `BatchDot`. We may instead want to change the `BatchDot` code to match Theano's backend implementation, if TensorFlow buys in to that implementation.

**Comment by zachmayer** [comment]
That's crazy!

**Comment by satchelspencer** [comment]
Interestingly, I have an alternate scenario where plaidml has different behavior from both theano and tf

```
from keras import backend as K

x = K.ones((12, 256, 1))
y = K.ones((12, 1, 256))
c = K.batch_dot(x, y)
print(K.int_shape(c))
```

 - plaidml @ 0.6.3: `(12, 256)`
 - tensorflow @ 1.14.0 `(12, 256, 256)`
 - theano @ 1.0.4 `(12, 256, 256)`

**Comment by dgkutnic** [comment]
Thanks for the example! Let me look into this.

**Comment by SleepProgger** [comment]
Just one more test to demonstrate the problems:
```
import os
import plaidml
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
import numpy as np
import keras.backend as K
import tensorflow
from keras.backend import tensorflow_backend as tf
import traceback
print("Plaidml version: %s" % plaidml.__version__)
data = [
    [np.ones((32, 1, 2), dtype="float32"), np.zeros((32, 2, 2), dtype="float32"), None],
    [np.ones((32, 68, 2), dtype="float32"), np.zeros((32, 2, 2), dtype="float32"), None],
    [np.ones((1, 2), dtype="float32"), np.zeros((1, 3, 2), dtype="float32"), (1, 2)] 
]

for params in data:
    print("\n%s" % ("#"*80))
    print("[?] Testing with: %s" % ", ".join(str(x.shape) if isinstance(x, np.ndarray) else str(x) for x in params))
    res_tf = res_k = None
    params_k = [K.constant(x, dtype=x.dtype) for x in params[:2]] + params[2:]
    params_tf = [tf.constant(x, dtype=x.dtype) for x in params[:2]] + params[2:]
    try:
        res_k = K.batch_dot(*params_k).eval()
    except Exception as e:
        print("Keras exception: %s" % traceback.format_exc())
    with tensorflow.Session():
        res_tf = tf.batch_dot(*params_tf).eval()
    if res_tf is not None:
        print("[?] Tensorflow shape: %s" % str(res_tf.shape))
    if res_k is not None:
        print("[?] Plaidml shape: %s" % str(res_k.shape))
    if res_k is not None and res_tf is not None:
        if res_k.shape != res_tf.shape:
            print("[-] Shape mismatch")
        else:
            print("[+] Shape match")
            print("[?] Difference: %.5f" % np.mean(np.sqrt(np.sum(np.square(res_tf - res_k)))))
```
=>
```
Plaidml version: 0.6.3

################################################################################
[?] Testing with: (32, 1, 2), (32, 2, 2), None
[?] Tensorflow shape: (32, 1, 2)
[?] Plaidml shape: (32, 2)
[-] Shape mismatch

################################################################################
[?] Testing with: (32, 68, 2), (32, 2, 2), None
Keras exception: Traceback (most recent call last):
  File "/home/nope/workspace/test/fs/batch_dot.py", line 43, in <module>
    res_k = K.batch_dot(*params_k).eval()
  File "/usr/lib/python3.7/site-packages/plaidml/keras/backend.py", line 765, in get_value
    shape = invoker.get_output_shape('out')
  File "/usr/lib/python3.7/site-packages/plaidml/__init__.py", line 1442, in get_output_shape
    return _Shape(self._ctx, _lib().plaidml_alloc_invoker_output_shape(self, name.encode()))
  File "/usr/lib/python3.7/site-packages/plaidml/__init__.py", line 777, in _check_err
    self.raise_last_status()
  File "/usr/lib/python3.7/site-packages/plaidml/library.py", line 131, in raise_last_status
    raise self.last_status()
plaidml.exceptions.Unknown: Type check failed due to mismatched tensor sizes: 68.000000 != 2.000000

[?] Tensorflow shape: (32, 68, 2)

################################################################################
[?] Testing with: (1, 2), (1, 3, 2), (1, 2)
[?] Tensorflow shape: (1, 3)
[?] Plaidml shape: (1, 3)
[+] Shape match
[?] Difference: 0.00000
```

Especially the exception seems interesting to me.

**Comment by dgkutnic** [comment]
Thank you @SleepProgger for the example.
Here's what we've decided:
We'll revert the PlaidML implementation of `BatchDot` to match the Theano implementation (and docs), and create a flag that will enable TensorFlow-*like* behavior. If TensorFlow eventually decides to merge with Theano's behavior, then we'll get rid of that code altogether. However, since we already have it, we can create the flag pretty easily.
I'll work on this within the next week and provide you with an update then.

**Comment by dgkutnic** [comment]
I've merged in the fixes I mentioned above, see #425 for more details

**Comment by zachmayer** [comment]
Thanks

**Comment by karan-jani** [comment]
Any update on this?
Have tried:
os.environ["PLAIDML_BATCHDOT_TF_BEHAVIOR"] = "True"

Still no luck.

**Comment by zachmayer** [comment]
The TF team claims this was fixed "in a later version", I will see if I can verify: https://github.com/tensorflow/tensorflow/issues/30846

**Comment by zachmayer** [comment]
It looks like the TF team wants to close this issue: https://github.com/tensorflow/tensorflow/issues/30846

**Comment by zachmayer** [comment]
Now that tensorflow is the only backend supported by keras, can we make sure plaidml is using a batchdot that works with tensorflow?
