### ISSUE TITLE
PlaidML-Setup: Specified Module Could Not be Found

### ISSUE THREAD

**Issue by Amokstakov** [plaidml/plaidml#877]
Hello,

I had PlaidML working with Keras and using on Spyder but suddenly I had to reset computer and I can not get it to work again.

Steps:
pip install tensorflow
pip install keras
pip install plaidml-keras plaidbench

Then run plaidml-setup:

OSError: [WinError 126] The specified module could not be found

![image](https://user-images.githubusercontent.com/53410236/73114526-66219380-3ee9-11ea-86fb-eb7654d42340.png)

Also tried using specific versions:

pip install tensorflow==2.0.0
pip install keras=2.2.4
pip install plaidml-keras==0.6.4 and still fails

Please help

**Comment by brianretford** [comment]
duplicate

**Comment by ansari-akram** [comment]
> Hello,
> 
> I had PlaidML working with Keras and using on Spyder but suddenly I had to reset computer and I can not get it to work again.
> 
> Steps:
> pip install tensorflow
> pip install keras
> pip install plaidml-keras plaidbench
> 
> Then run plaidml-setup:
> 
> OSError: [WinError 126] The specified module could not be found
> 
> ![image](https://user-images.githubusercontent.com/53410236/73114526-66219380-3ee9-11ea-86fb-eb7654d42340.png)
> 
> Also tried using specific versions:
> 
> pip install tensorflow==2.0.0
> pip install keras=2.2.4
> pip install plaidml-keras==0.6.4 and still fails
> 
> Please help
Did you get the solution to this problem?

**Comment by Amokstakov** [comment]
@ansari-akram 
The solution I implemented that seemed to work was making sure TF was <2.1, Keras  = 2.2.4 and pip install plaiml==0.6.4, plaidml-keras==0.6.4 and plaidbench==0.6.4

**Comment by Abd010** [comment]
Can you specify the exact version of TF which you used. I tried with 2.0 and my issue (which is same as above) did not resolve
